# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: LaunchApp
  displayName: Launch App
  
  jobs:
  - job: Preprocess
    displayName: Preprocess Confluence
    steps:
    - script: git clone https://github.com/Sahand1993/DataPreprocessor
    - script: cd DataPreprocessor && git checkout azure
    - script: mkdir datasets && touch datasets/empty.txt
    - script: mkdir preprocessed_datasets
    - script: cd DataPreprocessor && mvn spring-boot:run
      env:
        confluence_username: $(confluence_username)
        confluence_password: $(confluence_password)
  - deployment: LaunchApp
    dependsOn: Preprocess
    environment: Deployer.default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: flask run