# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: CreateTrigramDataSet
  displayName: Create Trigram Data Set
  jobs:
  - job: CloneRepo
    displayName: Clone dataPreprocessor repo
    steps:
    - script: git clone https://github.com/Sahand1993/DataPreprocessor 
    - script: cd DataPreprocessor && git checkout azure
  - job: RunPreprocessor
    displayName: Run Preprocessor
    dependsOn: CloneRepo
    steps:
    - script: cd DataPreprocessor && mvn spring-boot:run
  - job: Something
    steps:
    - script: echo hi
    
- stage: LaunchApp
  displayName: Launch App
  dependsOn: CreateTrigramDataSet
  jobs:
  - deployment: LaunchApp
    environment: Deployer.default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: flask run