trigger:
- master

pool:
 vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'neuralsearch'
  dockerRegistry: 'BraincourtDockerRegistry'

steps:
- task: Docker@2
  displayName: Build NeuralSearch Docker Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    arguments: '--build-arg confluence_username=$(confluence_username) --build-arg confluence_password=$(confluence_password) -t $(dockerRegistry)/$(imageName)'
- task: Docker@2
  displayName: Push NeuralSearch Docker Image
  inputs:
    repository: $(imageName)
    command: push
    containerRegistry: $(dockerRegistry)
    