trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-neuralsearch-docker'

steps:
- task: Docker@2
  displayName: Build NeuralSearch Docker image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
