trigger:
- master

pool:
 vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-neuralsearch-docker'

steps:
- task: Docker@2
  displayName: Build NeuralSearch Docker Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    arguments: '--build-arg confluence_username=$(confluence_username) --build-arg confluence_password=$(confluence_password)'
- task: Docker@2
  displayName: Push NeuralSearch Docker Image
  inputs:
    repository: $(imageName)
    command: push
    containerRegistry: BraincourtDockerRegistry
    